CREATE TABLE [dbo].[Contacts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR (50) NOT NULL,
	[Role] NVARCHAR (50) NOT NULL,
	[Email] NVARCHAR (50) NOT NULL,
	[Phone] NVARCHAR (50) NOT NULL
)
